---

- name: Adding apt repository
  apt_repository:
    codename: "{{ item.codename | default(omit) }}"
    filename: "{{ item.filename | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    repo: "{{ item.repo | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    update_cache: "{{ item.update_cache | default('yes') }}"
  with_items: "{{ apt_repositories }}"

- name: Add and remove deb822 formatted repositories
  deb822_repository:
    allow_downgrade_to_insecure: "{{ item.allow_downgrade_to_insecure | default(omit) }}"
    allow_insecure: "{{ item.allow_insecure | default(omit) }}"
    allow_weak: "{{ item.allow_weak | default(omit) }}"
    architectures: "{{ item.allow_weak | default(omit) }}"
    by_hash: "{{ item.by_hash | default(omit) }}"
    check_date: "{{ item.check_date | default(omit) }}"
    check_valid_until: "{{ item.check_valid_until | default(omit) }}"
    components: "{{ item.components | default(omit) }}"
    date_max_future: "{{ item.date_max_future | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    inrelease_path: "{{ item.inrelease_path | default(omit) }}"
    languages: "{{ item.languages | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    pdiffs: "{{ item.pdiffs | default(omit) }}"
    signed_by: "{{ item.signed_by | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    suites: "{{ item.suites | default(omit) }}"
    targets: "{{ item.targets | default(omit) }}"
    trusted: "{{ item.trusted | default(omit) }}"
    types: "{{ item.types | default(omit) }}"
    uris: "{{ item.uris | default(omit) }}"
  with_items: "{{ apt_deb822_repositories }}"
